version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fastify
    versions:
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
    - 3.14.2
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
